const express = require("express");
const auth = require("../middleware/auth");
const { roleGuard } = require("../middleware/role");
const { ObjectId } = require("mongodb");

module.exports = ({ interviewCollection, notificationCollection, messageCollection, applicationCollection, jobCollection }) => {
  const router = express.Router();
  router.get("/notifications", auth, async (req, res) => { const rows = await notificationCollection.find({ userId: req.user.id }).sort({ createdAt: -1 }).limit(50).toArray(); res.json({ success: true, data: rows }); });
  router.get("/messages", auth, async (req, res) => { const rows = await messageCollection.find({ $or: [{ senderId: req.user.id }, { recipientId: req.user.id }] }).sort({ createdAt: -1 }).limit(100).toArray(); res.json({ success: true, data: rows }); });
  router.post("/messages", auth, async (req, res) => { const recipientId = String(req.body?.recipientId || "").trim(); const body = String(req.body?.body || "").trim(); if (!recipientId || !body) return res.status(400).json({ success: false, message: "recipientId and body are required" }); const doc = { senderId: req.user.id, senderName: req.user.name || req.user.email, recipientId, body, readAt: null, createdAt: new Date() }; const result = await messageCollection.insertOne(doc); await notificationCollection.insertOne({ userId: recipientId, type: "message", title: "New message", body: `${doc.senderName} sent you a message.`, messageId: String(result.insertedId), readAt: null, createdAt: new Date() }); res.status(201).json({ success: true, data: { ...doc, _id: result.insertedId } }); });
  router.patch("/messages/:id/read", auth, async (req, res) => { const result = await messageCollection.updateOne({ _id: new ObjectId(req.params.id), recipientId: req.user.id }, { $set: { readAt: new Date() } }); res.json({ success: !!result.matchedCount }); });
  router.patch("/notifications/:id/read", auth, async (req, res) => { const result = await notificationCollection.updateOne({ _id: new ObjectId(req.params.id), userId: req.user.id }, { $set: { readAt: new Date() } }); res.json({ success: !!result.matchedCount }); });
  router.post("/interviews", auth, roleGuard("recruiter"), async (req, res) => { const { applicationId, startsAt, endsAt, meetingUrl, notes } = req.body || {}; if (!applicationId || !startsAt) return res.status(400).json({ success: false, message: "applicationId and startsAt are required" }); const application = await applicationCollection.findOne({ _id: new ObjectId(applicationId) }); if (!application) return res.status(404).json({ success: false, message: "Application not found" }); const job = await jobCollection.findOne({ _id: new ObjectId(application.jobId), recruiterId: req.user.id }); if (!job) return res.status(403).json({ success: false, message: "You do not own this job" }); const doc = { applicationId, jobId: String(application.jobId), recruiterId: req.user.id, seekerId: application.seekerId || application.userId, startsAt: new Date(startsAt), endsAt: endsAt ? new Date(endsAt) : null, meetingUrl: meetingUrl || null, notes: notes || null, status: "scheduled", createdAt: new Date(), updatedAt: new Date() }; const result = await interviewCollection.insertOne(doc); if (doc.seekerId) await notificationCollection.insertOne({ userId: doc.seekerId, type: "interview", title: "Interview scheduled", body: `An interview was scheduled for ${job.title || "your application"}.`, interviewId: String(result.insertedId), readAt: null, createdAt: new Date() }); res.status(201).json({ success: true, data: { ...doc, _id: result.insertedId } }); });
  router.get("/interviews/my", auth, async (req, res) => { const query = req.user.role === "recruiter" ? { recruiterId: req.user.id } : { seekerId: req.user.id }; const rows = await interviewCollection.find(query).sort({ startsAt: 1 }).toArray(); res.json({ success: true, data: rows }); });
  router.patch("/interviews/:id/cancel", auth, async (req, res) => { const query = req.user.role === "recruiter" ? { _id: new ObjectId(req.params.id), recruiterId: req.user.id } : { _id: new ObjectId(req.params.id), seekerId: req.user.id }; const result = await interviewCollection.updateOne(query, { $set: { status: "cancelled", updatedAt: new Date() } }); if (!result.matchedCount) return res.status(404).json({ success: false, message: "Interview not found" }); res.json({ success: true, message: "Interview cancelled" }); });
  return router;
};
